#!/bin/sh                                                                                                                                                                                                          
                                                                                                                                                                                                                   
file_check () {                                                                                                                                                                                                    
    NAME=$(whiptail --inputbox --nocancel "Merci d'entrer votre NOM : " 8 78 --title "Utilisateur" 3>&1 1>&2 2>&3)                                                                                                 
    FILENAME=ordinateur_de_$NAME                                                                                                                                                                                   
    if [ -e "$FILENAME" ]; then                                                                                                                                                                                    
        echo "Vous avez déjà lancé ce programme une fois. Pour le relancer veuillez supprimer le fichier ordinateur_de_$NAME\nSi vous n'y parvenez pas, contactez votre administrateur système." && exit           
    fi                                                                                                                                                                                                             
}                                                                                                                                                                                                                  
file_check                                                                                                                                                                                                         
                                                                                                                                                                                                                   
main () {                                                                                                                                                                                                          
    #NAME=$(whiptail --inputbox --nocancel "Merci d'entrer votre NOM : " 8 78 --title "Utilisateur" 3>&1 1>&2 2>&3)                                                                                                
    whiptail --title "Bienvenue" --msgbox "Bienvenue $NAME.\nVeuillez bien lire les instructions, Merci" 8 78                                                                                                      
    HOSTNAME=$(hostname)                                                                                                                                                                                           
    UBUNTU_VERSION=$(lsb_release -sr)                                                                                                                                                                              
    FIREFOX=$(firefox -v)                                                                                                                                                                                          
    THUNDERBIRD=$(thunderbird -v)                                                                                                                                                                                  
    LIBRE_OFFICE=$(libreoffice --version)                                                                                                                                                                          
    MAC_ADDR=$(ip link | awk '{print $2}')                                                                                                                                                                         
    IP_ADDR=$(ip a | grep "scope" | grep -Po '(?<=inet )[\d.]+')                                                                                                                                                   
                                                                                                                                                                                                                   
    echo "L'utilisateur de l'ordinateur est : $NAME" >> Infos                                                                                                                                                      
    echo "Nom d'hôte : $HOSTNAME" >> Infos                                                                                                                                                                         
    echo "La version d'Ubunutu est : Ubuntu $UBUNTU_VERSION" >> Infos                                                                                                                                              
    echo "MAC address:\n$MAC_ADDR" >> Infos                                                                                                                                                                        
    echo "IP address:\n$IP_ADDR" >> Infos                                                                                                                                                                          
    echo "$FIREFOX" >> Infos                                                                                                                                                                                       
    echo "$THUNDERBIRD" >> Infos                                                                                                                                                                                   
    echo "$LIBRE_OFFICE" >> Infos                                                                                                                                                                                  
    cat Infos | sed -e 's/^[ \t]*//' > ordinateur_de_$NAME                                                                                                                                                         
    rm -r Infos                                                                                                                                                                                                    
                                                                                                                                                                                                                   
    #ip addr show >> Info_IMEP                                                                                                                                                                                     
                                                                                                                                                                                                                   
    whiptail --title "Terminé" --msgbox "Vous trouverez un fichier nommé ordinateur_de_$NAME dans votre dossier Dossier Personnel.\nIl suffit de l'envoyer par mail à Balàzs pour qu'il puisse encoder la machine. \nSi vous ne le trouvez pas, n'hésitez pas à contacter Balàzs.\nMerci.\n" 12 78                                                                                                                                    
                                                                                                                                                                                                                   
    #If need to delete the file uncomment the folowing line:                                                                                                                                                       
    rm -- "$0"                                                                                                                                                                                                    
                                                                                                                                                                                                                   
}                                                                                                                                                                                                                  
main
exit
